services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-rta}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-rta}
      POSTGRES_DB: ${DB_NAME:-collaboration_app}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
    ports:
      - "5000:5432"
    restart: always

  server:
    build:
      context: ./server
    environment:
      - HOST=0.0.0.0
      - PORT=4000
      - DB_HOST=db
    ports:
      - "4000:4000"
    depends_on:
      - db
    restart: always

  client:
    build:
      context: ./client
    environment:
      - REACT_APP_API_URL=http://0.0.0.0:4000
      - REACT_APP_SOCKET_URL=http://0.0.0.0:4000
    ports:
      - "3000:3000"
    depends_on:
      - server
      - db
    restart: always

volumes:
  postgres_data:
